FAIL
Kernel panic in run: PANIC at ../../threads/synch.c:223 in lock_release(): assertion `lock_held_by_current_thread (lock)' failed.
Call stack: 0x80042133eb 0x8004209f73 0x8004218702 0x80042073bf
Translation of call stack:
0x00000080042133eb: debug_panic (lib/kernel/debug.c:32)
0x0000008004209f73: lock_release (threads/synch.c:225)
0x0000008004218702: l_thread_func (tests/threads/priority-donate-sema.c:59)
0x00000080042073bf: kernel_thread (threads/thread.c:571)
